# Generated by Django 3.2.16 on 2022-12-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('anneevente', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'annee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('iddetail', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('nofacture', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('datefacture', models.DateField()),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Histopays',
            fields=[
                ('idhistopays', models.AutoField(primary_key=True, serialize=False)),
                ('qtachat', models.IntegerField()),
            ],
            options={
                'db_table': 'histopays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Histoproduit',
            fields=[
                ('idhistoproduit', models.AutoField(primary_key=True, serialize=False)),
                ('qtvente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'histoproduit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('nompays', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('codeproduit', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'produit',
                'managed': False,
            },
        ),
    ]
