# Generated by Django 4.1.3 on 2022-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datevente',
            fields=[
                ('annee', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'datevente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('iddetail', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('nofacture', models.IntegerField(primary_key=True, serialize=False)),
                ('datefacturation', models.DateField()),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Histopays',
            fields=[
                ('idhistopays', models.AutoField(primary_key=True, serialize=False)),
                ('qtacheter', models.IntegerField()),
            ],
            options={
                'db_table': 'histopays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Histoproduit',
            fields=[
                ('idhistoprod', models.AutoField(primary_key=True, serialize=False)),
                ('qtvendu', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'histoproduit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('nompays', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('noproduit', models.IntegerField(primary_key=True, serialize=False)),
                ('nomproduit', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'produit',
                'managed': False,
            },
        ),
    ]
