# Generated by Django 4.1.3 on 2022-12-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'managed': True},
        ),
    ]
