# Generated by Django 4.1.3 on 2022-12-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_facture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'managed': False},
        ),
    ]
