# Generated by Django 3.2.16 on 2022-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_facture_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoPlotlyDashDashapp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=110, unique=True)),
                ('base_state', models.TextField()),
                ('creation', models.DateTimeField()),
                ('update', models.DateTimeField()),
                ('save_on_change', models.BooleanField()),
            ],
            options={
                'db_table': 'django_plotly_dash_dashapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoPlotlyDashStatelessapp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=110, unique=True)),
            ],
            options={
                'db_table': 'django_plotly_dash_statelessapp',
                'managed': False,
            },
        ),
    ]
